chore: refactor code to meet pylint style guidelines. WIP
rafaeelaudibert/Encryptor pull request #36
Opened 2021-10-31 16:17 UTC by chtnnh

#34 

Sorry, I may have jumped the gun on this @rafaeelaudibert but it was really bugging me.

Also, might need your help with setting up the GitHub CI to check for pylint errors

2021-10-31 19:25 UTC, rafaeelaudibert requested changes
This looks incredible @chtnnh! Thank you so much for contributing. I've left a review below, with some questions and suggested changes.

I think we could leave the CI for a next PR, just so that this PR doesn't get even bigger. What are your thoughts?

2021-10-31 19:25 UTC, rafaeelaudibert commented on encryptor/__init__.py
> +    # pylint: disable=unused-variable
Which variable are we ignoring?. This doesn't seem to be needed

2021-10-31 19:25 UTC, rafaeelaudibert commented on encryptor/__init__.py
> +        input_e = request.args.get("e", Rsa.DEFAULT_E)
👍🏻

2021-10-31 19:25 UTC, rafaeelaudibert commented on encryptor/encryptors/blowfish.py
> +        BadRequest.message = message
Why do we need this change? We could do it differently, though, calling `super.__init__(message)`

2021-10-31 19:25 UTC, rafaeelaudibert commented on encryptor/encryptors/vigenere.py
> +        Viegenere - Encrypt
```suggestion
        Vigenere - Encrypt
```

2021-10-31 19:25 UTC, rafaeelaudibert commented on encryptor/encryptors/vigenere.py
>          if key.isalpha():
We could use some spacing here
```suggestion
            tabula_recta = Vigenere.ALPHABET
        
        if key.isalpha():
```

2021-10-31 19:25 UTC, rafaeelaudibert commented on encryptor/encryptors/vigenere.py
> +        Viegenere - Decrypt
```suggestion
        Vigenere - Decrypt
```

2021-11-01 06:41 UTC, chtnnh commented on encryptor/__init__.py
> +    # pylint: disable=unused-variable
This is for the routes declared as functions. Pylint classifies them as unused-variables

2021-11-02 18:51 UTC, chtnnh commented on encryptor/encryptors/blowfish.py
> +        BadRequest.message = message
Linter threw an error I didn't fully understand. But this made it go away 😆 

LMK if this is unacceptable

2023-04-30 19:47 UTC, closed without merging